services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend/database:/app/database
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    env_file:
      - ./backend/.env
    networks:
      - app-network
    # ... 其余配置保持不变 ... 